### ISSUE TITLE
Issues with nextTick.ts & SSR

### ISSUE THREAD

**Issue by josemrodrigu** [joe223/tiny-swiper#77]
**Describe the bug**
Since the last version (`2.2.0`), our implementation (with server side rendering) returns the following error:

```
2022-02-11T15:17:14.232Z - error: uncaughtException: requestAnimationFrame is not defined
ReferenceError: requestAnimationFrame is not defined
    at /Users/josemrodrigu/Projects/andes-library-test/node_modules/tiny-swiper/lib/index.min.js:1:2592
    at /Users/josemrodrigu/Projects/andes-library-test/node_modules/tiny-swiper/lib/index.min.js:1:84
    at Object.<anonymous> (/Users/josemrodrigu/Projects/andes-library-test/node_modules/tiny-swiper/lib/index.min.js:1:201)
```

Checking nextTick.ts, I noticed that `nextFrame` and `cancelNextFrame` constants are defined outside `Tick()`. Of course, `Tick` is never executed on the server. Now that those connstants are defined at file scope, this bug can see the light.

I'll make a PR in order to support both client and server side implementations

**Expected behavior**
The error doesn't happen

**Information**
 - Tiny-Swiper Version: v2.2.0
 - OS: Every
 - Browser: Every
 - Reproduce example：I haven't any, only screen shots

<img width="824" alt="Captura de Pantalla 2022-02-11 a la(s) 12 27 10" src="https://user-images.githubusercontent.com/57464693/153619628-7129a1ce-c67d-403f-9476-e88432bf42e2.png">
<img width="690" alt="Captura de Pantalla 2022-02-11 a la(s) 12 27 18" src="https://user-images.githubusercontent.com/57464693/153619644-8d98a994-ce35-4879-9840-f5b4eadb3865.png">

**Comment by josemrodrigu** [comment]
@joe223 Any updates on this issue? do yo have a better solution for this scenario?

Thanks!

**Comment by themrdanielvp** [comment]
I am also having this issue..

**Comment by shkipan** [comment]
@joe223 , is there any chance this issue will be solved?
